<a href="https://colab.research.google.com/github/uditrawat23/Cousera-Introduction-to-Data-Science-in-Python/blob/master/Torch_basics_Day_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
import numpy as np

In [0]:
w =torch.zeros(5)

In [3]:
w

tensor([0., 0., 0., 0., 0.])

In [4]:
type(w)

torch.Tensor

In [0]:
r =np.zeros(5)

In [6]:
r

array([0., 0., 0., 0., 0.])

In [7]:
type(r)

numpy.ndarray

In [8]:
type(w)

torch.Tensor

In [0]:
f = torch.tensor([[1.0, 2.0],[3.0, 4.0]])

In [10]:
f

tensor([[1., 2.],
        [3., 4.]])

In [11]:
f.shape

torch.Size([2, 2])

In [12]:
type(f)

torch.Tensor

In [0]:
y =torch.rand((5,3))

In [14]:
y

tensor([[0.1517, 0.3232, 0.7044],
        [0.8168, 0.8115, 0.5135],
        [0.1194, 0.0335, 0.9091],
        [0.3071, 0.1283, 0.5194],
        [0.7881, 0.4686, 0.7087]])

In [15]:
y.shape

torch.Size([5, 3])

In [0]:
X = np.random.random((5, 3))

In [17]:
X.shape

(5, 3)

In [18]:
type(X)

numpy.ndarray

In [19]:
X


array([[0.24671569, 0.73723676, 0.84377237],
       [0.06740472, 0.02228096, 0.94163237],
       [0.94924964, 0.62016253, 0.98611034],
       [0.03067488, 0.43496996, 0.36005062],
       [0.11568707, 0.61788343, 0.19520407]])

In [20]:
torch.arange(2,10,2)

tensor([2, 4, 6, 8])

In [21]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [0]:
X = torch.rand(3, 2)

In [23]:
X

tensor([[0.0092, 0.2295],
        [0.3514, 0.3886],
        [0.7241, 0.3738]])

In [24]:
torch.exp(X)

tensor([[1.0092, 1.2580],
        [1.4211, 1.4749],
        [2.0629, 1.4532]])

In [25]:
X.exp()

tensor([[1.0092, 1.2580],
        [1.4211, 1.4749],
        [2.0629, 1.4532]])

In [26]:
X.sqrt()

tensor([[0.0957, 0.4791],
        [0.5928, 0.6234],
        [0.8509, 0.6114]])

In [0]:
B=torch.eye(3)

In [28]:
B

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [29]:
type(B)

torch.Tensor

In [30]:
B.add(5)

tensor([[6., 5., 5.],
        [5., 6., 5.],
        [5., 5., 6.]])

In [33]:
A = torch.randint( 0,100, (3, 3))
A

tensor([[ 7, 71, 16],
        [49, 71, 96],
        [19, 96, 53]])

In [34]:
A[1,1]

tensor(71)

In [35]:
A[:,1]

tensor([71, 71, 96])

In [36]:
A[1,:]

tensor([49, 71, 96])

In [37]:
A[:2, :2]

tensor([[ 7, 71],
        [49, 71]])

In [38]:
A[1:, 1:]

tensor([[71, 96],
        [96, 53]])

In [39]:
X = torch.tensor([1, 2, 3, 4])
X

tensor([1, 2, 3, 4])

In [41]:
X = X.repeat(3, 1) # repeat it 3 times along 0th dimension and 1 times along first dimension
X, X.shape

(tensor([[1, 2, 3, 4],
         [1, 2, 3, 4],
         [1, 2, 3, 4]]), torch.Size([3, 4]))

In [0]:
Y = X.view(2, 6)

In [43]:
Y

tensor([[1, 2, 3, 4, 1, 2],
        [3, 4, 1, 2, 3, 4]])

Matrix Multiplication

In [0]:
x1 = torch.tensor([[3,4],[2,1]])

In [45]:
x1

tensor([[3, 4],
        [2, 1]])

In [46]:
x1.shape

torch.Size([2, 2])

In [0]:
x2 = torch.tensor([[1,5],[3,7]])

In [48]:
x2

tensor([[1, 5],
        [3, 7]])

In [49]:
x2.shape

torch.Size([2, 2])

In [50]:
torch.mm(x1,x2)

tensor([[15, 43],
        [ 5, 17]])

Dimensions must be (m,n)*(n,k)

Resulting dimension (m,k)

In [0]:
a = torch.tensor([[0,2,4],[1,3,5]])

In [52]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [53]:
a.shape

torch.Size([2, 3])

In [0]:
b = torch.tensor([[6,7],[8,9],[10,11]])

In [55]:
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [56]:
b.shape

torch.Size([3, 2])

In [57]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [58]:
torch.manual_seed(12)

In [65]:
torch.manual_seed(0)

In [0]:
w1 = torch.eye(3)

In [67]:
w1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [62]:
torch.exp(w1)

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])

In [68]:
w1

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [0]:
w2 = torch.eye(3)

In [70]:
torch.exp_(w2)

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])

In [71]:
w2

tensor([[2.7183, 1.0000, 1.0000],
        [1.0000, 2.7183, 1.0000],
        [1.0000, 1.0000, 2.7183]])